import type { Metadata } from "next";
import Link from "next/link";
import { PageHead } from "@/components/site/page-head";
import { StatusBoard } from "@/components/site/status-board";

export const metadata: Metadata = {
  title: "Status",
  description:
    "Live status for Aletheore's own app API, generated by Aletheore's own endpoint health monitoring feature: the same public status API every AIR customer gets for their own repo.",
  alternates: { canonical: "/status" },
};

export default function StatusPage() {
  return (
    <>
      <PageHead eyebrow="Dogfooding, not a third-party status page" title="Aletheore's own status, monitored by Aletheore.">
        <p>
          This page is a plain client-side read of <code className="font-display text-[13px] text-ink">GET /v1/health/Aletheore/Aletheore</code>,
          the same public, unauthenticated status API every Aletheore AIR customer gets for their own repo. No separate uptime tool, no
          synthetic data: it is our own endpoint health monitoring feature, pointed at us.
        </p>
      </PageHead>
      <section className="mx-auto max-w-[1080px] px-8 pb-24">
        <StatusBoard />
        <p className="mt-6 max-w-[74ch] text-[12.5px] leading-[1.7] text-faint">
          Refreshes automatically every 60 seconds. Endpoints are discovered by scanning{" "}
          <a className="text-ink underline" href="https://github.com/Aletheore/Aletheore" rel="noopener">our own repo</a> with the Aletheore CLI, then
          checked every ~3 minutes, the identical mechanism behind the endpoint monitoring feature on{" "}
          <Link className="text-ink underline" href="/pricing">Aletheore AIR</Link>. Endpoints not checked in the last 15 minutes (removed routes, or
          previously-flagged endpoints that turned out not to be real) are dropped from this list rather than reported as up indefinitely.
        </p>
      </section>
    </>
  );
}
