#!/usr/bin/env python3
"""Extract curated, real Aletheore scan output into website/showcase-data.js."""

import argparse
import json


def summarize(evidence_path: str) -> dict:
    with open(evidence_path, encoding="utf-8") as f:
        data = json.load(f)
    return {
        "moduleCount": len(data["repository"]["modules"]),
        "dependencyEdgeCount": len(data["repository"]["dependency_graph"]["edges"]),
        "licenseFindingsCount": len(data["security"]["dependency_licenses"]["findings"]),
        "licenseChecked": data["security"]["dependency_licenses"]["checked"],
        "licenseReason": data["security"]["dependency_licenses"].get("reason"),
        "vulnerabilityFindingsCount": len(data["security"]["dependency_vulnerabilities"]["findings"]),
        "vulnerabilityChecked": data["security"]["dependency_vulnerabilities"]["checked"],
        "vulnerabilityReason": data["security"]["dependency_vulnerabilities"].get("reason"),
        "totalCommits": data["git"].get("total_commits"),
        "clusterCount": len(data["architecture"]["clusters"]),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--django", required=True)
    parser.add_argument("--express", required=True)
    parser.add_argument("--express-toon", required=True)
    parser.add_argument("--kubernetes", required=True)
    parser.add_argument("--kubernetes-scan-seconds", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    django = summarize(args.django)
    express = summarize(args.express)
    kubernetes = summarize(args.kubernetes)

    with open(args.express_toon, encoding="utf-8") as f:
        express_toon_bytes = len(f.read())
    with open(args.express, encoding="utf-8") as f:
        express_json_bytes = len(f.read())

    with open(args.kubernetes_scan_seconds, encoding="utf-8") as f:
        kubernetes_scan_seconds = int(f.read().strip().split(": ")[1])

    showcase = {
        "django": {
            **django,
            "commitSha": "3d34265d5d1b83fee5df3c1b6f55087b1a6a1ded",
        },
        "express": {
            **express,
            "commitSha": "ae6dd37680e3a00618d6c8a3e522f0ee4eeba1a4",
            "evidenceJsonBytes": express_json_bytes,
            "evidenceToonBytes": express_toon_bytes,
        },
        "kubernetes": {
            **kubernetes,
            "commitSha": "bd1a1b897340ef91595c36439fed49b9072f8b1d",
            "scanSeconds": kubernetes_scan_seconds,
            "clonedShallow": True,
        },
        "toonDemo": {
            "source": "Aletheore's own evidence.json/evidence.toon (self-scan, 2026-07-18)",
            "jsonTokens": 51137,
            "toonTokens": 27892,
            "tokenReductionPercent": 45.5,
            "jsonBytes": 217413,
            "toonBytes": 96694,
            "byteReductionPercent": 55.5,
        },
    }

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/generate-showcase-data.sh - do not hand-edit.\n")
        f.write("// Every value here traces to a real `aletheore scan` run against the\n")
        f.write("// pinned commit SHA recorded alongside it.\n")
        f.write(f"const SHOWCASE = {json.dumps(showcase, indent=2)};\n")


if __name__ == "__main__":
    main()
