// Generated by scripts/generate-showcase-data.sh - do not hand-edit.
// Every value here traces to a real `aletheore scan` run against the
// pinned commit SHA recorded alongside it.
const SHOWCASE = {
  "django": {
    "moduleCount": 3038,
    "dependencyEdgeCount": 9479,
    "licenseFindingsCount": 0,
    "licenseChecked": true,
    "licenseReason": null,
    "vulnerabilityFindingsCount": 0,
    "vulnerabilityChecked": true,
    "vulnerabilityReason": null,
    "totalCommits": 34793,
    "clusterCount": 896,
    "commitSha": "3d34265d5d1b83fee5df3c1b6f55087b1a6a1ded"
  },
  "express": {
    "moduleCount": 141,
    "dependencyEdgeCount": 0,
    "licenseFindingsCount": 0,
    "licenseChecked": true,
    "licenseReason": null,
    "vulnerabilityFindingsCount": 0,
    "vulnerabilityChecked": true,
    "vulnerabilityReason": null,
    "totalCommits": 6157,
    "clusterCount": 141,
    "commitSha": "ae6dd37680e3a00618d6c8a3e522f0ee4eeba1a4",
    "evidenceJsonBytes": 536022,
    "evidenceToonBytes": 194774
  },
  "kubernetes": {
    "moduleCount": 17499,
    "dependencyEdgeCount": 59174,
    "licenseFindingsCount": 40,
    "licenseChecked": true,
    "licenseReason": null,
    "vulnerabilityFindingsCount": 9,
    "vulnerabilityChecked": true,
    "vulnerabilityReason": null,
    "totalCommits": 1,
    "clusterCount": 12641,
    "commitSha": "bd1a1b897340ef91595c36439fed49b9072f8b1d",
    "scanSeconds": 355,
    "clonedShallow": true
  },
  "toonDemo": {
    "source": "Aletheore's own evidence.json/evidence.toon (self-scan, 2026-07-18)",
    "jsonTokens": 51137,
    "toonTokens": 27892,
    "tokenReductionPercent": 45.5,
    "jsonBytes": 217413,
    "toonBytes": 96694,
    "byteReductionPercent": 55.5
  }
};
